root: true
parser: typescript-eslint-parser
extends:
  - airbnb-base
  - prettier
plugins:
  - typescript
  - babel
  - prettier

rules:
  ###########
  # PLUGINS #
  ###########
  # IMPORT
  import/prefer-default-export: off
  # TYPESCRIPT
  typescript/interface-name-prefix:
    - error
    - always
  typescript/no-angle-bracket-type-assertion: error
  # typescript/explicit-member-accessibility: error
  typescript/no-unused-vars: error
  typescript/no-use-before-define:
    - error
    - functions: false
      variables: false
      typedefs: false
  ## blocked by https://github.com/nzakas/eslint-plugin-typescript/pull/23
  # typescript/member-ordering: error
  ##
  ## blocked by https://github.com/nzakas/eslint-plugin-typescript/issues/41
  # typescript/type-annotation-spacing: error
  ##

  # Babel
  babel/no-invalid-this: error

  ###########
  # BUILTIN #
  ###########
  no-underscore-dangle: off
  class-methods-use-this: warn
  no-useless-constructor: warn

  ###########
  # SPECIAL #
  ###########
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: es5
      semi: false
      parser: typescript
  no-restricted-syntax:
    - error
    # no-default-export
    - selector: ExportDefaultDeclaration
      message: Use of default exports is forbidden

parserOptions:
  sourceType: module
